#!/bin/bash

# Simple script to show URLs after starting services
echo ""
echo "🚀 ====================================== 🚀"
echo "    YouTube Downloader is Ready!"
echo "🚀 ====================================== 🚀"
echo ""
echo "📱 Frontend (Web UI):"
echo "   ➜ http://localhost:3000"
echo ""
echo "🔧 Backend API:"
echo "   ➜ http://localhost:8000"
echo "   ➜ API Docs: http://localhost:8000/docs"
echo ""
echo "💾 Database & Cache:"
echo "   ➜ PostgreSQL: localhost:5433"
echo "   ➜ Redis: localhost:6379"
echo ""
echo "🎉 Ready to download YouTube content!"
echo ""
echo "🛑 To stop all services:"
echo "   ➜ docker compose down"
echo "🚀 ====================================== 🚀"
echo ""
